### ISSUE TITLE
Passing a std string to printf doesn't compile with Ubuntu 14.04 Trusty's version of g++ (4.8.4) using the default options.

### ISSUE THREAD

**Issue by Poikilos** [expertmm/outputinspector#23]
This occurs in the nodeps branch using `./build.sh`.
```
.../mainwindow.cpp:29:44: error: cannot pass objects of non-trivially-copyable type 'const string {aka const class std::basic_string<char>}' through '...'
        printf( "cannot access %s\n", path ):
                                           ^
.../mainwindow.cpp:29:44: warning: format '%s' expects argument of type 'char*', but argument 2 has type 'const string {aka const std::basic_string<char>}' [-Wformat=]
```

where `...` is the full path.
