### ISSUE TITLE
Lambda doesn't compile with Ubuntu 14.04 Trusty's version of g++ (4.8.4) using the default options.

### ISSUE THREAD

**Issue by Poikilos** [expertmm/outputinspector#22]
Using build.sh yields:
```
* build:Release (/home/owner/git/outputinspector/build/outputinspector)
In file included from /home/owner/git/outputinspector/mainwindow.h:4:0,
                 from /home/owner/git/outputinspector/main.cpp:1:
/home/owner/git/outputinspector/settings.h: In function ‘void ltrim(std::string&)’:
/home/owner/git/outputinspector/settings.h:18:5: warning: lambda expressions only available with -std=c++11 or -std=gnu++11 [enabled by default]
     }));
     ^
/home/owner/git/outputinspector/settings.h:18:6: error: no matching function for call to ‘find_if(std::basic_string<char>::iterator, std::basic_string<char>::iterator, ltrim(std::string&)::__lambda0)’
     }));
      ^
/home/owner/git/outputinspector/settings.h:18:6: note: candidate is:
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /home/owner/git/outputinspector/settings.h:10,
                 from /home/owner/git/outputinspector/mainwindow.h:4,
                 from /home/owner/git/outputinspector/main.cpp:1:
/usr/include/c++/4.8/bits/stl_algo.h:4456:5: note: template<class _IIter, class _Predicate> _IIter std::find_if(_IIter, _IIter, _Predicate)
     find_if(_InputIterator __first, _InputIterator __last,
     ^
/usr/include/c++/4.8/bits/stl_algo.h:4456:5: note:   template argument deduction/substitution failed:
In file included from /home/owner/git/outputinspector/mainwindow.h:4:0,
                 from /home/owner/git/outputinspector/main.cpp:1:
/home/owner/git/outputinspector/settings.h: In substitution of ‘template<class _IIter, class _Predicate> _IIter std::find_if(_IIter, _IIter, _Predicate) [with _IIter = __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >; _Predicate = ltrim(std::string&)::__lambda0]’:
/home/owner/git/outputinspector/settings.h:18:6:   required from here
/home/owner/git/outputinspector/settings.h:18:6: error: template argument for ‘template<class _IIter, class _Predicate> _IIter std::find_if(_IIter, _IIter, _Predicate)’ uses local type ‘ltrim(std::string&)::__lambda0’
     }));
      ^
/home/owner/git/outputinspector/settings.h:18:6: error:   trying to instantiate ‘template<class _IIter, class _Predicate> _IIter std::find_if(_IIter, _IIter, _Predicate)’
/home/owner/git/outputinspector/settings.h: In function ‘void rtrim(std::string&)’:
/home/owner/git/outputinspector/settings.h:25:5: warning: lambda expressions only available with -std=c++11 or -std=gnu++11 [enabled by default]
     }).base(), s.end());
     ^
/home/owner/git/outputinspector/settings.h:25:6: error: no matching function for call to ‘find_if(std::basic_string<char>::reverse_iterator, std::basic_string<char>::reverse_iterator, rtrim(std::string&)::__lambda1)’
     }).base(), s.end());
      ^
/home/owner/git/outputinspector/settings.h:25:6: note: candidate is:
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /home/owner/git/outputinspector/settings.h:10,
                 from /home/owner/git/outputinspector/mainwindow.h:4,
                 from /home/owner/git/outputinspector/main.cpp:1:
/usr/include/c++/4.8/bits/stl_algo.h:4456:5: note: template<class _IIter, class _Predicate> _IIter std::find_if(_IIter, _IIter, _Predicate)
     find_if(_InputIterator __first, _InputIterator __last,
     ^
/usr/include/c++/4.8/bits/stl_algo.h:4456:5: note:   template argument deduction/substitution failed:
In file included from /home/owner/git/outputinspector/mainwindow.h:4:0,
                 from /home/owner/git/outputinspector/main.cpp:1:
/home/owner/git/outputinspector/settings.h: In substitution of ‘template<class _IIter, class _Predicate> _IIter std::find_if(_IIter, _IIter, _Predicate) [with _IIter = std::reverse_iterator<__gnu_cxx::__normal_iterator<char*, std::basic_string<char> > >; _Predicate = rtrim(std::string&)::__lambda1]’:
/home/owner/git/outputinspector/settings.h:25:6:   required from here
/home/owner/git/outputinspector/settings.h:25:6: error: template argument for ‘template<class _IIter, class _Predicate> _IIter std::find_if(_IIter, _IIter, _Predicate)’ uses local type ‘rtrim(std::string&)::__lambda1’
     }).base(), s.end());
      ^
/home/owner/git/outputinspector/settings.h:25:6: error:   trying to instantiate ‘template<class _IIter, class _Predicate> _IIter std::find_if(_IIter, _IIter, _Predicate)’
In file included from /home/owner/git/outputinspector/main.cpp:1:0:
/home/owner/git/outputinspector/mainwindow.h: At global scope:
/home/owner/git/outputinspector/mainwindow.h:106:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     bool m_DebugBadHints = true;
                            ^
/home/owner/git/outputinspector/mainwindow.h:107:39: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     const std::string COLLECT_REUSE = "REUSE"; /**< The target in the analyzed
                                       ^
/home/owner/git/outputinspector/mainwindow.h:111:37: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     const std::string STACK_LOWER = "LOWER"; /**< The code reference is further
                                     ^
/home/owner/git/outputinspector/mainwindow.h:115:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     const int TOKEN_FILE = 0; /**< def[TOKEN_FILE]
                            ^
/home/owner/git/outputinspector/mainwindow.h:119:31: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     const int TOKEN_PARAM_A = 1; /**< def[TOKEN_PARAM_A]
                               ^
/home/owner/git/outputinspector/mainwindow.h:124:31: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     const int TOKEN_PARAM_B = 2; /**< def[TOKEN_PARAM_B]
                               ^
/home/owner/git/outputinspector/mainwindow.h:127:34: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     const int TOKEN_END_PARAMS = 3; /**< def[TOKEN_END_PARAMS]
                                  ^
/home/owner/git/outputinspector/mainwindow.h:130:31: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     const int PARSE_COLLECT = 4; /**< def[PARSE_COLLECT]
                               ^
/home/owner/git/outputinspector/mainwindow.h:136:29: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     const int PARSE_STACK = 5; /**< def[PARSE_STACK]
                             ^
/home/owner/git/outputinspector/mainwindow.h:141:35: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     const int PARSE_DESCRIPTION = 5; /**< def[PARSE_STACK]
                                   ^
/home/owner/git/outputinspector/mainwindow.h:144:35: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     const int PARSE_PARTS_COUNT = 7;
                                   ^
/home/owner/git/outputinspector/mainwindow.h:145:37: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     const int ROLE_COLLECTED_FILE = OI_USER_ROLES_START;
                                     ^
/home/owner/git/outputinspector/mainwindow.h:146:48: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     const int ROLE_ROW = OI_USER_ROLES_START + 1;
                                                ^
/home/owner/git/outputinspector/mainwindow.h:147:48: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     const int ROLE_COL = OI_USER_ROLES_START + 2;
                                                ^
/home/owner/git/outputinspector/mainwindow.h:148:50: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     const int ROLE_LOWER = OI_USER_ROLES_START + 3;
                                                  ^
/home/owner/git/outputinspector/mainwindow.h:149:59: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     const int ROLE_COLLECTED_LINE = OI_USER_ROLES_START + 4;
                                                           ^
/home/owner/git/outputinspector/mainwindow.h:150:52: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     const int ROLE_DETAILS = OI_USER_ROLES_START + 5;
                                                    ^
/home/owner/git/outputinspector/mainwindow.h:153:38: error: ‘>>’ should be ‘> >’ within a nested template argument list
     std::list<std::vector<std::string>> enclosures;
                                      ^
In file included from /home/owner/git/outputinspector/main.cpp:1:0:
/home/owner/git/outputinspector/mainwindow.h:168:26: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     Settings* settings = nullptr;
                          ^
/home/owner/git/outputinspector/mainwindow.h:169:32: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     bool m_EnableTabDebugMsg = false;
                                ^
/home/owner/git/outputinspector/mainwindow.h:170:46: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     bool m_CompensateForKateTabDifferences = true;
                                              ^
/home/owner/git/outputinspector/mainwindow.h:171:26: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     int m_KateMajorVer = 0; /**< Use 2 to represent the 2.5.9 (kde3
                          ^
/home/owner/git/outputinspector/mainwindow.h:175:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     bool _verboseParsing = false;
                            ^
/home/owner/git/outputinspector/mainwindow.h:186:59: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     std::vector<std::string> m_ToDoFlags = {"TODO","FIXME"};
                                                           ^
/home/owner/git/outputinspector/mainwindow.h:187:27: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     std::string m_Error = "Error";
                           ^
/home/owner/git/outputinspector/mainwindow.h:188:29: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     std::string m_Warning = "Warning";
                             ^
/home/owner/git/outputinspector/mainwindow.h:189:34: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     std::string m_CommentToken = "//";
                                  ^
/home/owner/git/outputinspector/mainwindow.h:193:23: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     int m_LineCount = 0;
                       ^
/home/owner/git/outputinspector/mainwindow.h:194:31: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     int m_NonBlankLineCount = 0;
                               ^
/home/owner/git/outputinspector/mainwindow.h:199:26: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     bool m_IsJumpLower = true;
                          ^
/home/owner/git/outputinspector/mainwindow.h:210:19: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     int iErrors = 0;
                   ^
/home/owner/git/outputinspector/mainwindow.h:211:21: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     int iWarnings = 0;
                     ^
/home/owner/git/outputinspector/mainwindow.h:212:18: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     int iTODOs = 0;
                  ^
/home/owner/git/outputinspector/mainwindow.h:168:26: error: ‘nullptr’ was not declared in this scope
     Settings* settings = nullptr;
                          ^
/home/owner/git/outputinspector/mainwindow.h:186:59: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
     std::vector<std::string> m_ToDoFlags = {"TODO","FIXME"};
                                                           ^
In file included from /usr/include/c++/4.8/vector:62:0,
                 from /home/owner/git/outputinspector/settings.h:5,
                 from /home/owner/git/outputinspector/mainwindow.h:4,
                 from /home/owner/git/outputinspector/main.cpp:1:
/usr/include/c++/4.8/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_T1*, const _T2&) [with _T1 = std::basic_string<char>; _T2 = char]’:
/usr/include/c++/4.8/bits/stl_uninitialized.h:75:53:   required from ‘static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = const char*; _ForwardIterator = std::basic_string<char>*; bool _TrivialValueTypes = false]’
/usr/include/c++/4.8/bits/stl_uninitialized.h:117:41:   required from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = const char*; _ForwardIterator = std::basic_string<char>*]’
/usr/include/c++/4.8/bits/stl_uninitialized.h:258:63:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = const char*; _ForwardIterator = std::basic_string<char>*; _Tp = std::basic_string<char>]’
/usr/include/c++/4.8/bits/stl_vector.h:1206:27:   required from ‘void std::vector<_Tp, _Alloc>::_M_range_initialize(_ForwardIterator, _ForwardIterator, std::forward_iterator_tag) [with _ForwardIterator = const char*; _Tp = std::basic_string<char>; _Alloc = std::allocator<std::basic_string<char> >]’
/usr/include/c++/4.8/bits/stl_vector.h:1177:56:   required from ‘void std::vector<_Tp, _Alloc>::_M_initialize_dispatch(_InputIterator, _InputIterator, std::__false_type) [with _InputIterator = const char*; _Tp = std::basic_string<char>; _Alloc = std::allocator<std::basic_string<char> >]’
/usr/include/c++/4.8/bits/stl_vector.h:404:55:   required from ‘std::vector<_Tp, _Alloc>::vector(_InputIterator, _InputIterator, const allocator_type&) [with _InputIterator = const char*; _Tp = std::basic_string<char>; _Alloc = std::allocator<std::basic_string<char> >; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<std::basic_string<char> >]’
/home/owner/git/outputinspector/mainwindow.h:186:59:   required from here
/usr/include/c++/4.8/bits/stl_construct.h:83:7: error: invalid conversion from ‘char’ to ‘const char*’ [-fpermissive]
       ::new(static_cast<void*>(__p)) _T1(__value);
       ^
In file included from /usr/include/c++/4.8/string:53:0,
                 from /home/owner/git/outputinspector/settings.h:4,
                 from /home/owner/git/outputinspector/mainwindow.h:4,
                 from /home/owner/git/outputinspector/main.cpp:1:
/usr/include/c++/4.8/bits/basic_string.tcc:212:5: error:   initializing argument 1 of ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ [-fpermissive]
     basic_string<_CharT, _Traits, _Alloc>::
     ^
Error: building main failed.

```

**Comment by Poikilos** [comment]
It seems to be resolved by specifying gnu++14 in <https://github.com/poikilos/outputinspector/commit/f51186eb41af1a837e411eefae6cd77bdd28b5ef>
